modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="alexsmobsdelight"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.alexsmobsdelight]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alexsmobsdelight]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.alexsmobsdelight]]
    modId="alexsmobsup"
    type="required"
    versionRange="[${alexs_mobs_up_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alexsmobsdelight]]
    modId="citadelup"
    type="required"
    versionRange="[${citadel_up_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alexsmobsdelight]]
    modId="farmersdelight"
    type="required"
    versionRange="[${farmers_delight_version},)"
    ordering="AFTER"
    side="BOTH"
