modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="${mod_id}.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="BF_Meow, rawchickenNEG"
description='''Farmers Delight compat of Alex's Mobs, vanilla style.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="alexsmobsup"
    type="required"
    versionRange="[0.2.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="citadelup"
    type="required"
    versionRange="[0.1.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.3.3,)"
    ordering="AFTER"
    side="BOTH"
